version: '3.7'
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  api:
    container_name: api
    build:
      dockerfile: ./Dockerfile
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - SERVER_PORT=7070
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_HOST=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - CORS_ORIGIN=http://localhost:3000
    ports:
      - "8080:7070"